### ISSUE TITLE
Use 2D block and grid dimensions?

### ISSUE THREAD

**Issue by mhieronymus** [PolygonAndPixel/histogramming#2]
Not sure if useful. It would increase the number of possible threads.

**Comment by jllanfranchi** [comment]
that seems weird, i thought 1d / 2d / 3d was just there for programmer convenience if doing 1d / 2d or 3d work...

**Comment by mhieronymus** [comment]
Yes, the title is misleading since I was thinking about making the code easier to read. 
Let's say we max out the number of threads in a block (e.g. 1024 threads) and we max out the number of blocks in a grid (65535) in one dimension than we had 1024 x 65535 total threads. Using 2D and 3D grids could give more threads (additional 65535 blocks per dimension) but the performance won't be any better. 
See http://docs.nvidia.com/cuda/cuda-c-best-practices-guide/#thread-and-block-heuristics
Anyhow I close this issue since I see no benefits here.
