### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by mhieronymus** [PolygonAndPixel/histogramming#39]
Some results are wrong. I added the tests for comparison in `gpu_hist.py`.

Edit:
It seems like a simple 1D array as sample causes an error and a list of one array too. However not really a bug since those inputs are not supposed to be supported!?

Edit2:
There seems to be a race condition when using global memory.

**Comment by mhieronymus** [comment]
Most errors are rounding errors when using many edges and edges are given as integer. A rounding error might occur (if the width of the bins is about 1e-6 or smaller given `np.float32`) and therefore not every bin is equally spaced although the algorithm assumes it. This could be fixed by deleting `histogram_gmem_atomics` and `histogram_smem_atomics` and by using the algorithms with the edges instead although this is more slowly.

**Comment by jllanfranchi** [comment]
If one runs in fp32 mode, then one has to accept single precision accuracy, so if that's the only problem, I think it's okay. That said, there are better and worse ways to handle numbers in any precision (e.g. accumulating is to be avoided where possible).

**Comment by mhieronymus** [comment]
I wanted it to be more consistent with numpy's `histogramdd` but the algorithm with the edges does not help there either. fp32 simply isn't good enough. Anyhow I am rewriting my unit test and check it once again.

Update:
Using fp64 with shared memory works like a charm.

Update2:
The race condition is fixed (but not pushed yet). A `__syncthreads()` was missing.
All bugs should be fixed by now.

**Comment by mhieronymus** [comment]
Just pushed a working version with unit test.
